language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t meffowe24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true meffowe24/docker-react npm run test
